version: "3.3"
networks:
  xml_parser_network:
volumes:
  xml_parser_volume:

services:
  mysql_latest:
    image: mysql:latest
    volumes:
      - xml_parser_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: xml_parser_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - xml_parser_network

  debian_php8:
    container_name: debian_php8
    build: ./docker/debian
    volumes:
      - ./:/var/www/html/csv_parser
      - ./docker/vhost/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 80:80
    extra_hosts:
      - "xml_parser.test:127.0.0.1"
    networks:
      - xml_parser_network
